### ISSUE TITLE
[Feature] Use the OpenAPI specification to generate HTTP code

### ISSUE THREAD

**Issue by shenqidebaozi** [go-kratos/kratos#1609]
![image](https://user-images.githubusercontent.com/35397691/140450146-95b1dfc1-b9c6-4fbd-b7f7-f0b03c4e785c.png)

**Comment by shenqidebaozi** [comment]
@Windfarer

**Comment by Windfarer** [comment]
https://github.com/google/gnostic

**Comment by bandirsen** [comment]
@windfarer @shenqidebaozi, Sorry for my late join, I'm wraith on discord.
I against openapi 2 proto conversion idea, because it won't solve current grpc-web limititation, like I said on discord, current grpc-web is incomplete, some features like client streaming for file upload is not supported yet 

In one project, I use grpc for internal microservices communication, but because of those grpc-web limitation for public API (accessed by browser) I decide to use another framewok which generating server code directly from openapi file,  another reason is we only have few option to choose reverse-proxy server that support grpc-web, afaik, only Envoy support grpc-web natively, other reverse-proxy/api gateway server like Traefik, Caddy they are supporting grpc proxying but not grpc-web proxying

**Comment by Cluas** [comment]
https://github.com/google/gnostic-grpc, It might be possible to use this tool to convert openapi into a grpc service definition first, and then go through the original process
