### ISSUE TITLE
[Feature]grpcclient supports broadcast messages

### ISSUE THREAD

**Issue by mazhan465** [go-kratos/kratos#2764]
作为client向长连接网关发消息，因为发送对象分布在多个实例中，每次发送消息需要轮流请求每个server节点一次，能否在生成conn的时候增加广播option，invoke中对于广播conn轮流请求所有server节点

**Comment by shenqidebaozi** [comment]
this feature cannot be solved by the framework, or it is not a feature of the framework. You can obtain all the peer addresses through the registry and perform the broadcast behavior yourself. gRPC does not expose the relevant methods, allowing users to obtain channels. In addition, it seems that your problem is not a problem that RPC needs to solve, but rather a topic of message queues.". From your current description, the suggestions I can give are as follows.
