### ISSUE TITLE
v2.6.2 upgrade error

### ISSUE THREAD

**Issue by BeatsKitano** [go-kratos/kratos#2832]
#### What happened:
升级到v2.6.2后报错如下：
```
xxx/internal/biz imports
        github.com/go-kratos/kratos/v2/errors tested by
        github.com/go-kratos/kratos/v2/errors.test imports
        google.golang.org/grpc/test/grpc_testing: module google.golang.org/grpc@latest found (v1.55.0), but does not contain package google.golang.org/grpc/test/grpc_testing 
```

grpc同时已经升级到v1.55.0
```
upgraded google.golang.org/grpc v1.46.2 => v1.55.0
```

#### Anything else we need to know?:
如果将grpc降级为v1.46.2
```
go get -u google.golang.org/grpc@v1.46.2 
```
可正常运行

#### Environment:
- Kratos version (use `kratos -v`): v2.6.2
- Go version (use `go version`):1.20
- OS (e.g: `cat /etc/os-release`):macos
- Others:

**Comment by fifsky** [comment]
已经修正，将在下一个版本修正，目前先用google.golang.org/grpc  <1.55版本即可

**Comment by migmartri** [comment]
Hi, thanks for the fix. Any thoughts on when the change will be released? This issue is currently preventing us to perform some fairly [[1]](https://github.com/chainloop-dev/chainloop/issues/127) important [[2]](https://github.com/chainloop-dev/chainloop/pull/131) security upgrades in our dependencies.

Thanks!
