### ISSUE TITLE
google.golang.org/grpc is v1.55 no  test/grpc_testing

### ISSUE THREAD

**Issue by 1372143376** [go-kratos/kratos#2848]
google.golang.org/grpc/test/grpc_testing: module google.golang.org/grpc@latest found (v1.55.0), but does not contain package google.golang.org/grpc/test/grpc_testing

<img width="766" alt="image" src="https://github.com/grpc/grpc-go/assets/25361128/a0de574b-901c-4561-9c67-092dc0f047d2">

kratos  framework also references this package

**Comment by 1372143376** [comment]
<img width="830" alt="image" src="https://github.com/go-kratos/kratos/assets/25361128/981a58c3-39b9-4330-9441-fdd554369c83">

**Comment by shenqidebaozi** [comment]
#2824

**Comment by jayakrishna-allen** [comment]
@shenqidebaozi This issue is breaking some changes in our production codebase. Any idea when this change would get released?

**Comment by migmartri** [comment]
Hi, thanks for fixing the issue. Same problem as @jayakrishna-allen, this issue is currently preventing us to perform some fairly [1](https://github.com/chainloop-dev/chainloop/issues/127) important [2](https://github.com/chainloop-dev/chainloop/pull/131) security upgrades in our dependencies. Any thoughts on when a new release will be published?

Thanks!

**Comment by pplmx** [comment]
Please release a new version ASAP.
