### ISSUE TITLE
In version 1.0.0, Mergo moves to a vanity URL: dario.cat/mergo. Can update to the latest version?

### ISSUE THREAD

**Issue by yeqiaojun** [go-kratos/kratos#3149]

**Comment by amao12580** [comment]
same issuse

**Comment by amao12580** [comment]
please quick fix the require version

**Comment by Windfarer** [comment]
According to mergo README https://github.com/darccio/mergo?tab=readme-ov-file#100

If the vanity URL is causing issues in your project due to a dependency pulling Mergo - it isn't a direct dependency in your project - it is recommended to use [replace](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive) to pin the version to the last one with the old import URL:

```
replace github.com/imdario/mergo => github.com/imdario/mergo v0.3.16
```

**Comment by yangyile1990** [comment]
same issue.

when I want to update all my dependency packages to lastest version by this command:

admin@lele-de-MacBook-Pro uvxlan % go get -u ./...         
```           
go: github.com/imdario/mergo@v1.0.0: parsing go.mod:
        module declares its path as: dario.cat/mergo
                but was required as: github.com/imdario/mergo
        restoring github.com/imdario/mergo@v0.3.16
```

I got an error message.

So I check the reason:

admin@lele-de-MacBook-Pro uvxlan % go mod why github.com/imdario/mergo
```
# github.com/imdario/mergo
gitlab.yyle.com/golang/uvdemo.git/main_kratos/main_kratos_config
github.com/go-kratos/kratos/v2/config
github.com/imdario/mergo
```

So please fix it.
